#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if command -v python &> /dev/null; then
		python $script_dir/f1ala.py $@
	else
		if command -v python3 &> /dev/null; then
			python3 $script_dir/f1ala.py $@
		else
			echo "Both python and python3 command not found. Please install python."
		fi
fi
