# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# Origin b'https://github.com/id-bioinfo/TIPars.git', commit b'99fecc954878679f31f05162c136d483884772cf'
# ------------------------------------------------

package:
  files:
    - F1ALA.jar
    - lib/*
    - f1ala.py
    - f1ala
    - visual/*
  name: f1ala
  version: '1.0'
source:
  path: /mnt/c/Users/isaac/Documents/F1ALA
build:
  number: '6'
  script:
    - mkdir -p $PREFIX/bin
    - cp $RECIPE_DIR/F1ALA.jar $PREFIX/bin/
    - cp $RECIPE_DIR/f1ala $PREFIX/bin/
    - cp $RECIPE_DIR/f1ala.py $PREFIX/bin/
    - mkdir -p $PREFIX/bin/lib
    - cp $RECIPE_DIR/lib/* $PREFIX/bin/lib/
    - mkdir -p $PREFIX/bin/visual
    - cp $RECIPE_DIR/visual/* $PREFIX/bin/visual/
requirements:
  build: []
  run:
    - openjdk=11
test:
  commands:
    - echo "Success"
about:
  home: https://github.com/id-bioinfo/F1ALA
extra:
  copy_test_source_files: true
  final: true
